/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.production.jsonc --include-runtime=false --strict-vars=false --env-interface=ProductionBindings worker/worker-configuration.d.ts` (hash: 685b879970c1a58f8472283ae0041875)
interface __BaseEnv_ProductionBindings {
	ALLOWED_ORIGINS: string;
	GOOGLE_CLIENT_ID: string;
	MARKET_CLOSE: string;
	ANNOUNCEMENT: string;
	MARKET: DurableObjectNamespace<import("./index").Market>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Market";
	}
	interface Env extends __BaseEnv_ProductionBindings {}
}
interface ProductionBindings extends __BaseEnv_ProductionBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "GOOGLE_CLIENT_ID" | "MARKET_CLOSE" | "ANNOUNCEMENT">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}